name: promote-any
description: Promotes a canary environment
branding: {color: blue, icon: box}
inputs:
  environment: {description: environment name, required: true}
  AWS_ACCESS_KEY_ID_PROD: {description: prod aws access key id, required: true}
  AWS_SECRET_ACCESS_KEY_PROD: {description: prod aws secret access key, required: true}
  AWS_ACCESS_KEY_ID_CHINA: {description: china aws access key id, required: true}
  AWS_SECRET_ACCESS_KEY_CHINA: {description: china aws secret access key, required: true}
runs:
  using: composite
  steps:
    - name: promote
      shell: bash
      # language=bash
      run: |
        mkdir -p ~/.aws
        cat << EOF > ~/.aws/credentials
        [prodProfile]
        region=eu-west-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_PROD}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_PROD}}
        [chinaProfile]
        region=cn-north-1
        aws_access_key_id=${{inputs.AWS_ACCESS_KEY_ID_CHINA}}
        aws_secret_access_key=${{inputs.AWS_SECRET_ACCESS_KEY_CHINA}}
        EOF
        yarn --frozen-lockfile
        yarn promote:${{inputs.environment}}
        rm ~/.aws/credentials
